### ISSUE TITLE
Duplicate camera's

### ISSUE THREAD

**Issue by colinm** [jeanpaulsio/action-cable-signaling-server#28]
When testing the app local and on a server in production mode i see duplicate cameras per attendee,  so when i join video with 1 person we see 2 cams each, 3 = 3 cams each etc. This happens in chrome & ff, but not in safari. Can you point me in the right direction of what needs to change. I can add more info if needed.

**Comment by jeanpaulsio** [comment]
Would you be able to paste any relevant snippets of your code?

**Comment by colinm** [comment]
Sure it seems to happen when I'm using your code straight out of the repo
as well. One thing is I switch the database adapter to mySQL vs pg but
everything seems to work fine minus the double cams.

**Comment by michalg-** [comment]
Yup, https://github.com/jeanpaulsio/action-cable-signaling-server/blob/master/app/javascript/signaling_server.js#L107 that change adds two tracks, one with video and second audio, so every `video` element is duplicated.

**Comment by michalg-** [comment]
@colinm just created a fix to that issue https://github.com/jeanpaulsio/action-cable-signaling-server/pull/31

**Comment by colinm** [comment]
Awesome michalg! I had no idea what to look for in the js, I figured it was in the js but I'm not too crafty in js.
