### ISSUE TITLE
Insecure approach

### ISSUE THREAD

**Issue by victorhazbun** [jeanpaulsio/action-cable-signaling-server#3]
Your API credentials are exposed in the website. Could you please show us how to accomplish the same goal in a secure way (by not exposing credentials in the web). Thanks.

**Comment by jeanpaulsio** [comment]
Yup!

https://github.com/jeanpaulsio/rails-video-chat-app/issues/3

A good approach would be to use environment variables. In the process of revamping this repo to be a little more clear about that
