### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/action-cable-signaling-server#5]
I am working on Safari support for this project. I want to do so without introducing any dependencies. Opening the issue to track progress, gather feedback ETC.

[Twilio has safari support in their js library. Using this as inspiration. ](https://github.com/twilio/twilio-video.js/blob/581cd23cf309361739e6652dfdf5e3b803c41b0b/lib/util/support.js)

`navigator.webkitGetUserMedia` 

Notes: 
- [ ] Safari does not allow GetuserMedia requests from a non-https site. (Including localhost) - You can work around this by using an [ngrok](https://ngrok.com/) secure tunnel in development

**Comment by javierojeda94** [comment]
How is this going?

**Comment by jeanpaulsio** [comment]
![image](https://user-images.githubusercontent.com/8096483/83093406-38de2100-a054-11ea-8a9a-8ea25e45d353.png)

I believe this was actually fixed with https://github.com/jeanpaulsio/action-cable-signaling-server/commit/f2a950a46dc98235ca8a485b6586a8416688180f 😀
