### ISSUE TITLE
If not using heroku?

### ISSUE THREAD

**Issue by mices** [jeanpaulsio/action-cable-signaling-server#7]
What from the instructions can be omitted if not using Heroku I dunno why you default to Heroku since not everyone uses it I'd guess most don't

**Comment by Johnsalzarulo** [comment]
I've never deployed anywhere but Heroku - however - there isn't anything Heroku specific here. 

It should be good to go if you have redis and action cable all set up and configure the asset pipeline as described. 

It would be amazing if you'd submit a PR with instructions on deploying in other contexts. 

Feel free to update this issue with any specific questions - I'll do my best to help!

**Comment by mices** [comment]
If not using heroku how would cable.yml otherwise be configured? Thanks
 config/cable.yml

production:
  adapter: redis
  url: ${REDISTOGO_URL}

**Comment by Johnsalzarulo** [comment]
Ahhh - Great question.

So this is not specific to this repo - This is needed for Rails Action Cable in general, in order for Action cable to work you need a redis database along with your regular production database. 

To help you specifically it would be helpful to know where you are trying to deploy... 

For example [this article](https://unboxed.co/blog/actioncable-on-aws/) has some help on setting up action cable on AWS - but there may be some nuance depending on your deployment environment. 

So, if you just look into "Action Cable Config for **Insert Production Environment** that should get you going in the right direction.

**Comment by mices** [comment]
Self hosted using passenger nginx module Production server is running freebsd latest release

**Comment by mices** [comment]
I did this before in development, setting up a redis server for signaling but I forgot what it was all about, I'm as described in your intro Don't really know what's going on yet

**Comment by jeanpaulsio** [comment]
@mices - maybe this article will point you in the right direction?

https://www.phusionpassenger.com/library/config/nginx/action_cable_integration/

**Comment by mices** [comment]
Thanks I'll have to get setup in development first anyway, i dunno why mentioned production environment

**Comment by mices** [comment]
Sorry Just getting back to this I'm sure there's good reasons why you don't include the pages controller or the suggested contents in routes.rb so can i ask why

**Comment by jeanpaulsio** [comment]
I'm unsure what you're asking about. what should be included in the pages controller or the routes file?

**Comment by mices** [comment]
Just to make it work out of the box Not important It displays the Yay! page out of the box because the routes aren't setup yet The signalling server has to be mounted I saw the suggestion that I mount it as a subdomain (that would require a match in my routes) but I see I can mount it at any path ~ thanks
