### ISSUE TITLE
trying to integrate into my own app

### ISSUE THREAD

**Issue by mices** [jeanpaulsio/action-cable-signaling-server#8]
Hi Sorry for the delay I was debugging my site for a  couple of days I got this working but trying to integrate into my own app is another story  I left out your pages controller and put the contents of your application.html.erb into my conversations/show view (mailboxer) Now nothing happens when I click join room submit buttom If I incude the scripts cable and signaling-server on conversations/show page the webcam operating light turns on when the page loads without clicking the join room buttom but still nothing happens when i click join room I had a routing error until I changed POST /sessions to POST /conversations/sessions I notice there's no javascript include tag in your code so how does the signaling-server script get included?

**Comment by jeanpaulsio** [comment]
so the `signaling-server.js` file gets included because of this line `//= require_tree .` in the application.js file

i'm still not really certain why it's not working in your personal project. one idea might be to go through the entire readme again? if you have a public repository, i can pull it down and have a better sense of what isn't working

**Comment by mices** [comment]
If I put //= require signaling-server.js in application.js then my webcam operating light goes with loading of my site's home page

**Comment by jeanpaulsio** [comment]
right - so you need to load the javascript only for a certain page, i'm guessing

there's always putting <script> tags on the bottom of the page that you're rendering and putting the signaling-server.js script there?

**Comment by mices** [comment]
Well I'm not using //= require_tree . because something I use (I forget what maybe bootstrap or jquery) requires that I don't Should be no difference between having a javascript_include_tag on top or <script> tags containing the script on bottom, right?
